services:
    SendGrid:
        class: \SendGrid
        arguments: [ '%nurschool_sendgrid.api_key%' ]

    nurschool_sendgrid.provider:
        class: Nurschool\Bundle\NurschoolSendgridBundle\Provider\SendgridProvider
        arguments:
            $disableDelivery: '%nurschool_sendgrid.disable_delivery%'
            $redirectTo: '%nurschool_sendgrid.redirect_to%'
            $sandbox: '%nurschool_sendgrid.sandbox%'