services:
    SendGrid:
        class: \SendGrid
        arguments: [ '%nurschool_sendgrid.api_key%' ]

    nurschool_sendgrid.event_dispatcher:
        class: Nurschool\Bundle\NurschoolSendgridBundle\EventDispatcher\SendgridEventDispatcher
        autowire: true

    nurschool_sendgrid.provider:
        class: Nurschool\Bundle\NurschoolSendgridBundle\Provider\SendgridProvider
        arguments:
            - '@SendGrid'
            - '@nurschool_sendgrid.event_dispatcher'
            - '%nurschool_sendgrid.disable_delivery%'
            - '%nurschool_sendgrid.redirect_to%'
            - '%nurschool_sendgrid.sandbox%'